# -*- coding: utf-8 -*-
"""DL models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyO6U-PkfjhCdGfajRoZA8Tkc4bZtok5

"""

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

# Load the dataset
dataset_name = 'imagenet_v2/matched-frequency'
test_dataset, info = tfds.load(name=dataset_name, split='test', with_info=True, as_supervised=True)

# Preprocess the data
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = info.features['label'].num_classes

def preprocess_image(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.keras.applications.resnet50.preprocess_input(image)
    return image, label

test_dataset = test_dataset.map(preprocess_image).batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)

# Load ResNet50 model with pre-trained ImageNet weights
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))

# Add custom classifier with ResNet50
x = GlobalAveragePooling2D()(base_model.output)
x = Dense(1024, activation='relu')(x)
output = Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

# Freeze the layers of ResNet50
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Define a checkpoint callback
checkpoint = ModelCheckpoint('resnet50_imagenet_subset.h5', monitor='val_loss', save_best_only=True, verbose=1)

# Evaluate the model on the test dataset
test_loss, test_accuracy = model.evaluate(test_dataset)

print(f'Test Loss: {test_loss}')
print(f'Test Accuracy: {test_accuracy}')

# Save the trained model
model.save('resnet50_imagenet.h5')
print("Model saved successfully.")

"""train resnet-50 on mnist"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Conv2D, BatchNormalization, Activation, MaxPooling2D, GlobalAveragePooling2D, Dense, Add
from tensorflow.keras.models import Model
from tensorflow.keras.datasets import mnist
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.utils import to_categorical

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_train, x_test = x_train / 255.0, x_test / 255.0

# Add a channel dimension to the images
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Define identity block
def identity_block(X, filters):
    F1, F2, F3 = filters

    X_shortcut = X

    X = Conv2D(filters=F1, kernel_size=(1, 1), strides=(1, 1), padding='valid')(X)
    X = BatchNormalization()(X)
    X = Activation('relu')(X)

    X = Conv2D(filters=F2, kernel_size=(3, 3), strides=(1, 1), padding='same')(X)
    X = BatchNormalization()(X)
    X = Activation('relu')(X)

    X = Conv2D(filters=F3, kernel_size=(1, 1), strides=(1, 1), padding='valid')(X)
    X = BatchNormalization()(X)

    X = Add()([X, X_shortcut])
    X = Activation('relu')(X)

    return X

# Define convolutional block
def convolutional_block(X, filters, s=2):
    F1, F2, F3 = filters

    X_shortcut = X

    X = Conv2D(filters=F1, kernel_size=(1, 1), strides=(s, s), padding='valid')(X)
    X = BatchNormalization()(X)
    X = Activation('relu')(X)

    X = Conv2D(filters=F2, kernel_size=(3, 3), strides=(1, 1), padding='same')(X)
    X = BatchNormalization()(X)
    X = Activation('relu')(X)

    X = Conv2D(filters=F3, kernel_size=(1, 1), strides=(1, 1), padding='valid')(X)
    X = BatchNormalization()(X)

    X_shortcut = Conv2D(filters=F3, kernel_size=(1, 1), strides=(s, s), padding='valid')(X_shortcut)
    X_shortcut = BatchNormalization()(X_shortcut)

    X = Add()([X, X_shortcut])
    X = Activation('relu')(X)

    return X

# Define ResNet-50 model
def ResNet50(input_shape=(28, 28, 1), classes=10):
    X_input = Input(input_shape)

    X = Conv2D(64, (7, 7), strides=(2, 2), padding='same')(X_input)
    X = BatchNormalization()(X)
    X = Activation('relu')(X)
    X = MaxPooling2D((3, 3), strides=(2, 2))(X)

    X = convolutional_block(X, filters=[64, 64, 256], s=1)
    X = identity_block(X, filters=[64, 64, 256])
    X = identity_block(X, filters=[64, 64, 256])

    X = convolutional_block(X, filters=[128, 128, 512], s=2)
    X = identity_block(X, filters=[128, 128, 512])
    X = identity_block(X, filters=[128, 128, 512])
    X = identity_block(X, filters=[128, 128, 512])

    X = convolutional_block(X, filters=[256, 256, 1024], s=2)
    X = identity_block(X, filters=[256, 256, 1024])
    X = identity_block(X, filters=[256, 256, 1024])
    X = identity_block(X, filters=[256, 256, 1024])
    X = identity_block(X, filters=[256, 256, 1024])
    X = identity_block(X, filters=[256, 256, 1024])

    X = convolutional_block(X, filters=[512, 512, 2048], s=2)
    X = identity_block(X, filters=[512, 512, 2048])
    X = identity_block(X, filters=[512, 512, 2048])

    X = GlobalAveragePooling2D()(X)
    X = Dense(classes, activation='softmax')(X)

    model = Model(inputs=X_input, outputs=X, name='ResNet50')
    return model

# Create ResNet-50 model
model = ResNet50()

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Define a checkpoint callback
checkpoint = ModelCheckpoint('resnet50_mnist.h5', monitor='val_loss', save_best_only=True, verbose=1)

# Train the model
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=2, batch_size=32, callbacks=[checkpoint])

# Save the trained model
model.save('resnet50_mnist.h5')
print("Model saved successfully.")

"""transform to lite model"""

import tensorflow as tf

# Load the saved model
saved_model_path = 'resnet50_mnist.h5'
model = tf.keras.models.load_model(saved_model_path)

# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model
tflite_model_path = 'resnet50_mnist.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

print("Model converted and saved as:", tflite_model_path)

"""transform to lite model"""

import tensorflow as tf

# Load the saved Keras model
saved_model_path = 'resnet50_imagenet.h5'
# saved_model_path = 'resnet50_mnist.h5'
model = tf.keras.models.load_model(saved_model_path)

# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model
tflite_model_path = 'resnet50_imagenet.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

# tflite_model_path = 'resnet50_mnist.tflite'
# with open(tflite_model_path, 'wb') as f:
#     f.write(tflite_model)

print("Model converted and saved as:", tflite_model_path)

"""inference lite mnist accuracy"""

import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load MNIST dataset
(_, _), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_test = x_test / 255.0

# Reshape images to (num_samples, height, width, channels)
x_test = np.expand_dims(x_test, axis=-1)

# Convert labels to one-hot encoding
y_test = to_categorical(y_test, 10)

# Load the TensorFlow Lite model
tflite_model_path = 'resnet50_imagenet.tflite'
# tflite_model_path = 'resnet50_mnist.tflite'
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Function to perform inference on a single image
def predict(image):
    interpreter.set_tensor(input_details[0]['index'], image)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    return output_data

# Function to calculate accuracy
def calculate_accuracy(images, labels):
    correct = 0
    total = len(images)
    for i in range(len(images)):
        image = np.expand_dims(images[i], axis=0).astype(np.float32)
        predicted = np.argmax(predict(image))
        true_label = np.argmax(labels[i])
        if predicted == true_label:
            correct += 1
    accuracy = correct / total
    return accuracy

# Calculate accuracy on the test dataset
accuracy = calculate_accuracy(x_test, y_test)
print("Accuracy of the TensorFlow Lite model:", accuracy)

"""inference only lite model"""

import numpy as np
import tensorflow as tf

# Load the TensorFlow Lite model
tflite_model_path = 'resnet50_imagenet.tflite'
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

image_data = np.random.rand(1, 224, 224, 3).astype(np.float32)

# Perform inference
interpreter.set_tensor(input_details[0]['index'], image_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

predicted_class = np.argmax(output_data)

print("Predicted class:", predicted_class)

"""inference on lite mnist"""

import tensorflow as tf
import numpy as np
import cv2

# Load the TensorFlow Lite model
tflite_model_path = 'resnet50_mnist.tflite'
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Load sample image data (replace this with your own image data)
sample_image = np.random.rand(1, 224, 224, 3).astype(np.float32)

# Resize the sample image to match the expected input shape (28x28) of the model
resized_sample_image = cv2.resize(sample_image[0], (28, 28))

# Convert the image to grayscale
resized_sample_image_gray = cv2.cvtColor(resized_sample_image, cv2.COLOR_BGR2GRAY)

# Expand dimensions to match the model's input shape (add batch dimension and channel dimension)
resized_sample_image_gray = np.expand_dims(resized_sample_image_gray, axis=0)
resized_sample_image_gray = np.expand_dims(resized_sample_image_gray, axis=-1)

# Perform inference
interpreter.set_tensor(input_details[0]['index'], resized_sample_image_gray)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

# Post-process the output if needed
predicted_class = np.argmax(output_data)

print("Predicted class:", predicted_class)

"""Train ResNet-50 - fp16"""

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Enable mixed precision training
from tensorflow.keras import mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)

# Define constants
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 5
MODEL_SAVE_PATH = 'resnet50_mnist_quantized.h5'

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocess the datasets
x_train = tf.image.resize(x_train, [IMG_SIZE, IMG_SIZE])
x_train = tf.repeat(x_train, 3, -1)
x_train = tf.expand_dims(x_train, axis=0)
x_train = tf.repeat(x_train, len(y_train), axis=0)
x_train = x_train / 255.0

x_test = tf.image.resize(x_test, [IMG_SIZE, IMG_SIZE])
x_test = tf.repeat(x_test, 3, -1)
x_test = tf.expand_dims(x_test, axis=0)
x_test = tf.repeat(x_test, len(y_test), axis=0)
x_test = x_test / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Load the ResNet50 model with pre-trained ImageNet weights
model = ResNet50(weights='imagenet', include_top=True, classes=1000)

# Ensure the model uses the policy by wrapping the optimizer with a LossScaleOptimizer
opt = Adam()
opt = mixed_precision.LossScaleOptimizer(opt)

# Compile the model
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

# Define a checkpoint callback
checkpoint = ModelCheckpoint(MODEL_SAVE_PATH, monitor='val_loss', save_best_only=True, verbose=1)

# Train the model
model.fit(
    x_train, y_train,
    validation_data=(x_test, y_test),
    epochs=EPOCHS,
    callbacks=[checkpoint]
)

"""transform to lite model"""

import tensorflow as tf

# Load the saved model
saved_model_path = 'resnet50_mnist_quantized.h5'
model = tf.keras.models.load_model(saved_model_path)

# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model
tflite_model_path = 'resnet50_mnist_quanlized.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

print("Model converted and saved as:", tflite_model_path)

"""inference on lite mnist quantized"""

import tensorflow as tf
import numpy as np

# Load the TensorFlow Lite model
tflite_model_path = 'resnet50_mnist_quantized.tflite'
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Load sample image data (replace this with your own image data)
sample_image = np.random.rand(1, 224, 224, 3).astype(np.float32)

# Perform inference
interpreter.set_tensor(input_details[0]['index'], sample_image)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

# Post-process the output if needed
predicted_class = np.argmax(output_data)

print("Predicted class:", predicted_class)

"""Keras - ResNet-50 inference example"""

import keras
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

model = ResNet50(weights='imagenet')

img_path = 'elephant.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
# decode the results into a list of tuples (class, description, probability)
# (one such list for each sample in the batch)
print('Predicted:', decode_predictions(preds, top=3)[0])
# Predicted: [(u'n02504013', u'Indian_elephant', 0.82658225), (u'n01871265', u'tusker', 0.1122357), (u'n02504458', u'African_elephant', 0.061040461)]

"""Keras - VGG-16 inference example"""

import keras
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)

img_path = 'elephant.jpg'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

features = model.predict(x)

"""transform saved_resnet.pb to the resnet-lite"""

import tensorflow as tf

model_dir = 'resnet_50/saved_model.pb'

# Load the SavedModel
model = tf.saved_model.load(model_dir)

# Create a converter
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir)

# Convert the model
tflite_model = converter.convert()

# Save the TensorFlow Lite model
with open('resnet_50.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model has been successfully converted to TensorFlow Lite and saved as model.tflite")

"""Usage of resnet model"""

m = tf.keras.Sequential([
    hub.KerasLayer("https://www.kaggle.com/models/tensorflow/resnet-50/frameworks/TensorFlow2/variations/classification/versions/1")
])
m.build([None, 224, 224, 3])

"""Inference of lite model"""

import tensorflow as tf
import numpy as np
from PIL import Image

# Load TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path="resnet_50.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Open image
image = Image.open('elephant.jpg').resize((224, 224))

# Preprocess the image
input_data = np.expand_dims(image, axis=0)

# Perform the inference
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()

# Get the result
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

"""train and save mobilenet keras - mnist"""

import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Dropout, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.datasets import mnist
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.image import img_to_array, array_to_img

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_train, x_test = x_train / 255.0, x_test / 255.0

# Resize images to meet the minimum input size requirement of MobileNet
x_train_resized = tf.image.resize(x_train[..., tf.newaxis], (32, 32))
x_test_resized = tf.image.resize(x_test[..., tf.newaxis], (32, 32))

# Convert labels to one-hot encoding
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

# Define MobileNet model architecture
def create_mobilenet_model():
    input_tensor = Input(shape=(32, 32, 1))
    base_model = tf.keras.applications.MobileNet(input_shape=(32, 32, 1), include_top=False, weights=None)
    x = base_model(input_tensor)
    x = GlobalAveragePooling2D()(x)
    x = Dropout(0.5)(x)
    output_tensor = Dense(10, activation='softmax')(x)
    model = Model(inputs=input_tensor, outputs=output_tensor)
    return model

# Create MobileNet model
model = create_mobilenet_model()

# Compile the model
model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Define a checkpoint callback
checkpoint = ModelCheckpoint('mobilenet_mnist.h5', monitor='val_loss', save_best_only=True, verbose=1)

# Train the model
model.fit(x_train_resized, y_train, validation_data=(x_test_resized, y_test), epochs=5, batch_size=32, callbacks=[checkpoint])

# Save the trained model
model.save('mobilenet_mnist.h5')
print("Model saved successfully.")

"""train mobilenet keras on imagenet"""

import tensorflow as tf
import tensorflow_datasets as tfds
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint

# Load the dataset
dataset_name = 'imagenet_v2/matched-frequency'
test_dataset, info = tfds.load(name=dataset_name, split='test', with_info=True, as_supervised=True)

# Preprocess the data
IMG_SIZE = 224
BATCH_SIZE = 32
NUM_CLASSES = info.features['label'].num_classes

def preprocess_image(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = tf.keras.applications.mobilenet.preprocess_input(image)
    return image, label

test_dataset = test_dataset.map(preprocess_image).batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)

# Load MobileNet model with pre-trained ImageNet weights
base_model = MobileNet(weights='imagenet', include_top=False, input_shape=(IMG_SIZE, IMG_SIZE, 3))

# Add custom classifier on top of MobileNet
x = GlobalAveragePooling2D()(base_model.output)
x = Dense(1024, activation='relu')(x)
output = Dense(NUM_CLASSES, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

# Freeze the layers of MobileNet
for layer in base_model.layers:
    layer.trainable = False

# Compile the model
model.compile(optimizer=Adam(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Define a checkpoint callback
checkpoint = ModelCheckpoint('mobilenet_imagenet_subset.h5', monitor='val_loss', save_best_only=True, verbose=1)

# Train the model
model.fit(test_dataset, epochs=5, callbacks=[checkpoint])

# Save the trained model
model.save('mobilenet_imagenet_subset_final.h5')
print("Model saved successfully.")

"""transform to lite model"""

import tensorflow as tf

# Load the saved model
saved_model_path = '../../../Downloads/mobilenet_mnist.h5'
# saved_model_path = 'mobilenet_imagenet.h5'
model = tf.keras.models.load_model(saved_model_path)

# Convert the model to TensorFlow Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the TensorFlow Lite model
tflite_model_path = '../../../Downloads/mobilenet_mnist.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

# tflite_model_path = 'mobilenet_imagenet.tflite'
# with open(tflite_model_path, 'wb') as f:
#     f.write(tflite_model)

print("Model converted and saved as:", tflite_model_path)

"""inference accuracy lite"""

import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

# Load MNIST test dataset
(_, _), (x_test, y_test) = mnist.load_data()

# Normalize pixel values to be between 0 and 1
x_test = x_test / 255.0

# Reshape images to (num_samples, height, width, channels)
x_test = np.expand_dims(x_test, axis=-1)

# Convert labels to one-hot encoding
y_test = to_categorical(y_test, 10)

# Load the TensorFlow Lite model
interpreter = tf.lite.Interpreter(model_path='mobilenet_imagenet.tflite')
# interpreter = tf.lite.Interpreter(model_path='mobilenet_mnist.tflite')
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Function to perform inference on a single image
def predict(image):
    interpreter.set_tensor(input_details[0]['index'], image)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    return output_data

# Function to calculate accuracy
def calculate_accuracy(images, labels):
    correct = 0
    total = len(images)
    for i in range(len(images)):
        image = np.expand_dims(images[i], axis=0).astype(np.float32)
        predicted = np.argmax(predict(image))
        true_label = np.argmax(labels[i])
        if predicted == true_label:
            correct += 1
    accuracy = correct / total
    return accuracy

# Calculate accuracy on the test dataset
accuracy = calculate_accuracy(x_test, y_test)
print("Accuracy of the TensorFlow Lite model:", accuracy)

"""inference lite model"""

import numpy as np
import tensorflow as tf

# Load the TensorFlow Lite model
interpreter = tf.lite.Interpreter(model_path='mobilenet_imagenet_subset_final.tflite')
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Load sample image data (replace this with your own image data)
image_data = np.random.rand(1, 224, 224, 3).astype(np.float32)

# Perform inference
interpreter.set_tensor(input_details[0]['index'], image_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])

predicted_class = np.argmax(output_data)

print("Predicted class:", predicted_class)

"""transform saved_mobilenet.pb to the mobilenet-lite"""

import tensorflow as tf

model_dir = 'mobilenet/saved_model.pb'

# Load the SavedModel
model = tf.saved_model.load(model_dir)

# Create a converter
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir)

# Convert the model
tflite_model = converter.convert()

# Save the TensorFlow Lite model
with open('mobilenet.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model has been successfully converted to TensorFlow Lite and saved as model.tflite")

"""Usage of mobilenet"""

m = tf.keras.Sequential([
    hub.KerasLayer("https://www.kaggle.com/models/google/mobilenet-v2/frameworks/TensorFlow2/variations/035-128-classification/versions/2")
])
m.build([None, 128, 128, 3])

"""Inference mobilenet lite"""

import tensorflow as tf
import numpy as np
from PIL import Image

# Load TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path="../../../Downloads/mobilenet_mnist.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Open image
image = Image.open('elephant.jpg').resize((32, 32))

# Convert image to grayscale
image = image.convert('L')

# Convert image to numpy array and normalize to [0, 1]
input_data = np.array(image, dtype=np.float32) / 255.0

# Expand dimensions to match the expected input shape
input_data = np.expand_dims(input_data, axis=0)
input_data = np.expand_dims(input_data, axis=3)  # Add channel dimension

# Perform the inference
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()

# Get the result
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)

"""transform saved_bert.pb to the bert-lite"""

import tensorflow as tf

model_dir = 'bert/saved_model.pb'

# Load the SavedModel
model = tf.saved_model.load(model_dir)

# Create a converter
converter = tf.lite.TFLiteConverter.from_saved_model(model_dir)

# Convert the model
tflite_model = converter.convert()

# Save the TensorFlow Lite model
with open('bert.tflite', 'wb') as f:
    f.write(tflite_model)

print("Model has been successfully converted to TensorFlow Lite and saved as model.tflite")

"""Usage of BERT"""

text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer(
    "https://kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/en-uncased-preprocess/versions/3")
encoder_inputs = preprocessor(text_input)
encoder = hub.KerasLayer(
    "https://www.kaggle.com/models/tensorflow/bert/frameworks/TensorFlow2/variations/bert-en-uncased-l-10-h-128-a-2/versions/2",
    trainable=True)
outputs = encoder(encoder_inputs)
pooled_output = outputs["pooled_output"]      # [batch_size, 128].
sequence_output = outputs["sequence_output"]  # [batch_size, seq_length, 128].

embedding_model = tf.keras.Model(text_input, pooled_output)
sentences = tf.constant(["(your text here)"])
print(embedding_model(sentences))

"""inference on BERT-lite"""

import tensorflow as tf
import numpy as np

# Load TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path="bert_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Prepare input data
# input data --> input ids, input mask, and segment ids
input_ids = np.array([[101, 2023, 2003, 1037, 2742, 102]], dtype=np.int32)
input_mask = np.array([[1, 1, 1, 1, 1, 1]], dtype=np.int32)
segment_ids = np.array([[0, 0, 0, 0, 0, 0]], dtype=np.int32)

# Set the tensor values
interpreter.set_tensor(input_details[0]['index'], input_ids)
interpreter.set_tensor(input_details[1]['index'], input_mask)
interpreter.set_tensor(input_details[2]['index'], segment_ids)

# Invoke the interpreter
interpreter.invoke()

# Get the output tensor
output_data = interpreter.get_tensor(output_details[0]['index'])

print(output_data)

"""tiny bert train"""

import os
import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification
from transformers import glue_convert_examples_to_features

# Load pre-trained BERT tokenizer and model
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name, from_pt=True)

# Provide the path to the downloaded MRPC dataset
data_dir = "mrpc_data.msi"

# Convert MRPC dataset for BERT
train_dataset = glue_convert_examples_to_features(data_dir, tokenizer, max_length=128, task='mrpc')

# Fine-tune BERT on MRPC dataset
epochs = 3
optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
metric = tf.keras.metrics.SparseCategoricalAccuracy('accuracy')
model.compile(optimizer=optimizer, loss=loss, metrics=[metric])

model.fit(train_dataset, epochs=epochs)

# Save the fine-tuned model
model.save_pretrained("bert_finetuned")

# Convert the TensorFlow model to TensorFlow Lite
converter = tf.lite.TFLiteConverter.from_saved_model("bert_finetuned")
tflite_model = converter.convert()

# Save the TensorFlow Lite model to a file
with open("bert_finetuned.tflite", "wb") as f:
    f.write(tflite_model)

"""tiny bert lite inference"""

import numpy as np
import tensorflow as tf

# Load the TensorFlow Lite model.
interpreter = tf.lite.Interpreter(model_path="tinybert_finetuned.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Example input data (tokenized and converted to input_ids and attention_masks)
input_ids = [101, 1045, 2342, 2003, 2025, 1037, 2204, 1012, 102, 2003, 2025, 1037, 2204, 1012, 102]  # Example input_ids
attention_mask = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]  # Example attention_mask

# Resize input tensor if necessary
input_shape = input_details[0]['shape']
input_data = np.array(input_ids, dtype=np.int32)
input_data = np.resize(input_data, input_shape)
input_mask = np.array(attention_mask, dtype=np.int32)
input_mask = np.resize(input_mask, input_shape)

# Set input tensor values
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.set_tensor(input_details[1]['index'], input_mask)

# Run inference
interpreter.invoke()

# Get output tensor
output_data = interpreter.get_tensor(output_details[0]['index'])

# Perform any post-processing if necessary
# For example, if you have a classification task, you may need to apply softmax
# output_data = tf.nn.softmax(output_data, axis=-1)

# Print or use the output
print(output_data)